/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabalhofinalpoo.view;

import com.mycompany.trabalhofinalpoo.model.GerenciadorLancamentoCSV;
import com.mycompany.trabalhofinalpoo.model.Lancamento;
import com.mycompany.trabalhofinalpoo.model.Receita;
import com.mycompany.trabalhofinalpoo.model.Despesas;
import javax.swing.JDialog;
import javax.swing.JOptionPane; 
import java.util.List;

/**
 *
 * @author anamo
 */
public class tela extends javax.swing.JFrame {
       private GerenciadorLancamentoCSV gerenciador = new GerenciadorLancamentoCSV();
  private JDialog telaReceita;
    private JDialog telaDespesa;
    private JDialog telaExtrato;
   
    public tela() {
     initComponents(); 
        jBtDespesa.addActionListener(e -> abrirTelaReceita());
        jBtReceita.addActionListener(e -> abrirTelaDespesa()); 
        jBtExtrato.addActionListener(e -> abrirTelaExtrato());

        jBtSalvarR.addActionListener(e -> salvarReceita());
        jBtSalvarD.addActionListener(e -> salvarDespesa());

        jBtSairR.addActionListener(e -> TelaReceita.dispose());
        jBtSairD.addActionListener(e -> TelaDespesa.dispose());
        jBtSairE.addActionListener(e -> TelaExtrato.dispose());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaReceita = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFvalorR = new javax.swing.JTextField();
        jTFDescR = new javax.swing.JTextField();
        jTFCategoriaR = new javax.swing.JTextField();
        jTFDataR = new javax.swing.JTextField();
        jBtSalvarR = new javax.swing.JButton();
        jBtSairR = new javax.swing.JButton();
        TelaDespesa = new javax.swing.JDialog();
        jTFCategoriaD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFDataD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jBtSalvarD = new javax.swing.JButton();
        jBtSairD = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTFvalorD = new javax.swing.JTextField();
        jTFDescD = new javax.swing.JTextField();
        TelaExtrato = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAExtrato = new javax.swing.JTextArea();
        jBtSairE = new javax.swing.JButton();
        jBtReceita = new javax.swing.JButton();
        jBtDespesa = new javax.swing.JButton();
        jBtExtrato = new javax.swing.JButton();

        jLabel1.setText("Valor:");

        jLabel2.setText("Descrição:");

        jLabel3.setText("Categoria:");

        jLabel4.setText("Data:");

        jBtSalvarR.setText("Salvar");

        jBtSairR.setText("Sair");

        javax.swing.GroupLayout TelaReceitaLayout = new javax.swing.GroupLayout(TelaReceita.getContentPane());
        TelaReceita.getContentPane().setLayout(TelaReceitaLayout);
        TelaReceitaLayout.setHorizontalGroup(
            TelaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaReceitaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(TelaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaReceitaLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jTFvalorR, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TelaReceitaLayout.createSequentialGroup()
                        .addGroup(TelaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtSalvarR)
                            .addGroup(TelaReceitaLayout.createSequentialGroup()
                                .addGroup(TelaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(TelaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFDescR, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFCategoriaR, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFDataR, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(50, 50, 50)
                        .addComponent(jBtSairR)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        TelaReceitaLayout.setVerticalGroup(
            TelaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaReceitaLayout.createSequentialGroup()
                .addGroup(TelaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaReceitaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaReceitaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTFvalorR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGroup(TelaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFDescR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TelaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFCategoriaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TelaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTFDataR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(TelaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtSalvarR)
                    .addComponent(jBtSairR))
                .addGap(54, 54, 54))
        );

        jLabel5.setText("Valor:");

        jLabel6.setText("Descrição:");

        jBtSalvarD.setText("Salvar");

        jBtSairD.setText("Sair");

        jLabel7.setText("Categoria:");

        jLabel8.setText("Data:");

        javax.swing.GroupLayout TelaDespesaLayout = new javax.swing.GroupLayout(TelaDespesa.getContentPane());
        TelaDespesa.getContentPane().setLayout(TelaDespesaLayout);
        TelaDespesaLayout.setHorizontalGroup(
            TelaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaDespesaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(TelaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaDespesaLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jTFvalorD, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TelaDespesaLayout.createSequentialGroup()
                        .addGroup(TelaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtSalvarD)
                            .addGroup(TelaDespesaLayout.createSequentialGroup()
                                .addGroup(TelaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(TelaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFDescD, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFCategoriaD, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFDataD, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(50, 50, 50)
                        .addComponent(jBtSairD)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        TelaDespesaLayout.setVerticalGroup(
            TelaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaDespesaLayout.createSequentialGroup()
                .addGroup(TelaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaDespesaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaDespesaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTFvalorD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGroup(TelaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTFDescD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TelaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTFCategoriaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TelaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTFDataD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(TelaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtSalvarD)
                    .addComponent(jBtSairD))
                .addGap(54, 54, 54))
        );

        jLabel9.setText("Extrato");

        jTAExtrato.setColumns(20);
        jTAExtrato.setRows(5);
        jScrollPane1.setViewportView(jTAExtrato);

        jBtSairE.setText("Sair");

        javax.swing.GroupLayout TelaExtratoLayout = new javax.swing.GroupLayout(TelaExtrato.getContentPane());
        TelaExtrato.getContentPane().setLayout(TelaExtratoLayout);
        TelaExtratoLayout.setHorizontalGroup(
            TelaExtratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaExtratoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(TelaExtratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaExtratoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(TelaExtratoLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtSairE)
                        .addGap(25, 25, 25))))
        );
        TelaExtratoLayout.setVerticalGroup(
            TelaExtratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaExtratoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(TelaExtratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jBtSairE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtReceita.setText("Nova Despesa");

        jBtDespesa.setText("Nova Receita");

        jBtExtrato.setText("Extrato");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtReceita)
                    .addComponent(jBtDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jBtDespesa)
                .addGap(33, 33, 33)
                .addComponent(jBtReceita)
                .addGap(36, 36, 36)
                .addComponent(jBtExtrato)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  private void abrirTelaReceita() {
        TelaReceita.pack(); 
        TelaReceita.setLocationRelativeTo(this); 
        TelaReceita.setVisible(true);
    }

    private void abrirTelaDespesa() {
        TelaDespesa.pack();
        TelaDespesa.setLocationRelativeTo(this);
        TelaDespesa.setVisible(true);
    }

    private void abrirTelaExtrato() {
       
        jTAExtrato.setText("");
        StringBuilder extratoText = new StringBuilder();
        extratoText.append("--- Extrato de Lançamentos ---\n\n");

        List<Lancamento> lancamentos = gerenciador.carregarLancamentos();

        if (lancamentos.isEmpty()) {
            extratoText.append("Nenhum lançamento registrado.\n");
        } else {
            for (Lancamento l : lancamentos) {
                String tipo = l.isReceita() ? "Receita" : "Despesa";
                extratoText.append("ID: ").append(l.getId()).append("\n");
                extratoText.append("Tipo: ").append(tipo).append("\n");
                extratoText.append("Valor: R$ ").append(String.format("%.2f", l.getValor())).append("\n");
                extratoText.append("Descrição: ").append(l.getDescricao()).append("\n");
                extratoText.append("Categoria: ").append(l.getCategoria()).append("\n");
                extratoText.append("Data: ").append(l.getDataHora()).append("\n");
                extratoText.append("----------------------------\n");
            }
        }
        jTAExtrato.setText(extratoText.toString());

        TelaExtrato.pack();
        TelaExtrato.setLocationRelativeTo(this);
        TelaExtrato.setVisible(true);
    }

    private void salvarReceita() {
        try {
            
            double valor = Double.parseDouble(jTFvalorR.getText());
            String descricao = jTFDescR.getText();
            String categoria = jTFCategoriaR.getText();
            String data = jTFDataR.getText();

            int id = gerenciador.getProximoId();

            Receita novaReceita = new Receita(id, valor, descricao, categoria, data);

            gerenciador.salvarLancamento(novaReceita);

            JOptionPane.showMessageDialog(this, "Receita salva com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            jTFvalorR.setText("");
            jTFDescR.setText("");
            jTFCategoriaR.setText("");
            jTFDataR.setText("");
            TelaReceita.dispose();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Erro: O valor deve ser um número válido.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(), "Erro de Validação", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar receita: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    private void salvarDespesa() {
        try {
            
            double valor = Double.parseDouble(jTFvalorD.getText());
            String descricao = jTFDescD.getText();
            String categoria = jTFCategoriaD.getText();
            String data = jTFDataD.getText();

            int id = gerenciador.getProximoId();
  
            Despesas novaDespesa = new Despesas(id, valor, descricao, categoria, data);
        
            gerenciador.salvarLancamento(novaDespesa);
          
            JOptionPane.showMessageDialog(this, "Despesa salva com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            jTFvalorD.setText("");
            jTFDescD.setText("");
            jTFCategoriaD.setText("");
            jTFDataD.setText("");
            TelaDespesa.dispose();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Erro: O valor deve ser um número válido.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(), "Erro de Validação", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar despesa: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog TelaDespesa;
    private javax.swing.JDialog TelaExtrato;
    private javax.swing.JDialog TelaReceita;
    private javax.swing.JButton jBtDespesa;
    private javax.swing.JButton jBtExtrato;
    private javax.swing.JButton jBtReceita;
    private javax.swing.JButton jBtSairD;
    private javax.swing.JButton jBtSairE;
    private javax.swing.JButton jBtSairR;
    private javax.swing.JButton jBtSalvarD;
    private javax.swing.JButton jBtSalvarR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAExtrato;
    private javax.swing.JTextField jTFCategoriaD;
    private javax.swing.JTextField jTFCategoriaR;
    private javax.swing.JTextField jTFDataD;
    private javax.swing.JTextField jTFDataR;
    private javax.swing.JTextField jTFDescD;
    private javax.swing.JTextField jTFDescR;
    private javax.swing.JTextField jTFvalorD;
    private javax.swing.JTextField jTFvalorR;
    // End of variables declaration//GEN-END:variables
}
