/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabalhofinalpoo.view;

import com.mycompany.trabalhofinalpoo.model.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

/**
 *
 * @author anamo
 */
public class Tela extends javax.swing.JFrame {
    private JTable tabela;
    private DefaultTableModel modeloTabela;
    private GerenciadorLancamentoCSV gerenciador;
    private JDialog formularioDialog;
    private JTextField campoDescricao, campoValor, campoCategoria;
    private JComboBox<String> comboTipo;
    private JButton botaoSalvar;

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents(); 
        initComponents();
        gerenciador = new GerenciadorLancamentoCSV();
        setupTabela();
        setupDialog();
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jTFDesc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFvalor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFCategoria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jBtNovoLancamento = new javax.swing.JButton();
        jBtSair = new javax.swing.JButton();

        jDialog1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jDialog1WindowActivated(evt);
            }
        });
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Descrição:");
        jDialog1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 40, 71, -1));
        jDialog1.getContentPane().add(jTFDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 37, 114, -1));

        jLabel2.setText("Valor:");
        jDialog1.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 83, 37, -1));
        jDialog1.getContentPane().add(jTFvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 80, 114, -1));

        jLabel3.setText("Categoria:");
        jDialog1.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 123, 62, -1));
        jDialog1.getContentPane().add(jTFCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 120, 114, -1));

        jLabel4.setText("Tipo:");
        jDialog1.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 174, 37, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 171, 114, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtNovoLancamento.setText("Novo Lançamento");
        jBtNovoLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtNovoLancamentoActionPerformed(evt);
            }
        });

        jBtSair.setText("sair");
        jBtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtNovoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jBtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtNovoLancamento)
                    .addComponent(jBtSair))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jDialog1WindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog1WindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_jDialog1WindowActivated

    private void jBtNovoLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtNovoLancamentoActionPerformed
        // TODO add your handling code here:
          
        campoDescricao.setText("");
        campoValor.setText("");
        campoCategoria.setText("");
        formularioDialog.setVisible(true);
    }//GEN-LAST:event_jBtNovoLancamentoActionPerformed

    private void jBtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSairActionPerformed
        // TODO add your handling code here:
            System.exit(0);
    }//GEN-LAST:event_jBtSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtNovoLancamento;
    private javax.swing.JButton jBtSair;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTFCategoria;
    private javax.swing.JTextField jTFDesc;
    private javax.swing.JTextField jTFvalor;
    // End of variables declaration//GEN-END:variables

  private void salvarLancamento() {
        String descricao = campoDescricao.getText();
        String valorStr = campoValor.getText();
        String categoria = campoCategoria.getText();
        String tipoSelecionado = (String) comboTipo.getSelectedItem();

        if (descricao.isEmpty() || valorStr.isEmpty() || categoria.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            double valor = Double.parseDouble(valorStr);
            int id = gerenciador.getProximoId();
            String dataHora = java.time.LocalDateTime.now().toString();
            Lancamento lancamento;

            if ("Receita".equalsIgnoreCase(tipoSelecionado)) {
                lancamento = new Receita(id, valor, descricao, categoria, dataHora);
            } else {
                lancamento = new Despesas(id, valor, descricao, categoria, dataHora);
            }

            gerenciador.salvarLancamento(lancamento);
            formularioDialog.dispose();
            atualizarTabela();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Valor inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

      private void setupDialog() {
        formularioDialog = new JDialog(this, "Novo Lançamento", true);
        formularioDialog.setLayout(new GridLayout(5, 2, 10, 10));
        formularioDialog.setSize(400, 250);
        formularioDialog.setLocationRelativeTo(this);

        campoDescricao = new JTextField();
        campoValor = new JTextField();
        campoCategoria = new JTextField();
        comboTipo = new JComboBox<>(new String[]{"Receita", "Despesa"});
        botaoSalvar = new JButton("Salvar");

        formularioDialog.add(new JLabel("Descrição:"));
        formularioDialog.add(campoDescricao);
        formularioDialog.add(new JLabel("Valor:"));
        formularioDialog.add(campoValor);
        formularioDialog.add(new JLabel("Categoria:"));
        formularioDialog.add(campoCategoria);
        formularioDialog.add(new JLabel("Tipo:"));
        formularioDialog.add(comboTipo);
        formularioDialog.add(new JLabel(""));
        formularioDialog.add(botaoSalvar);

        botaoSalvar.addActionListener(e -> salvarLancamento());
    }

 private void setupTabela() {
        modeloTabela = new DefaultTableModel(new String[]{"ID", "Tipo", "Valor", "Descrição", "Categoria", "DataHora"}, 0);
        tabela = new JTable(modeloTabela);
        add(new JScrollPane(tabela), BorderLayout.CENTER);
    }

   private void atualizarTabela() {
        modeloTabela.setRowCount(0);
        List<Lancamento> lista = gerenciador.carregarLancamentos();
        for (Lancamento l : lista) {
            String tipo = l.isReceita() ? "Receita" : "Despesa";
            modeloTabela.addRow(new Object[]{l.getId(), tipo, l.getValor(), l.getDescricao(), l.getCategoria(), l.getDataHora()});
        }
    }